# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
