# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181221_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 8, 39, 5, 110452, tzinfo=utc)),
        ),
    ]
